<a href="https://colab.research.google.com/github/Minh0237/DA/blob/main/Py_27_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[10, 1, 2],
              [9, 7 ,4],
              [0, 2, 1]])

B = np.array([[2, 3, 4],
              [0, 4, 2],
              [3, 2, 1]])

t1 = np.dot(A, B)
print(t1)

t21 = np.dot(B, A)
t21T = t21.T
t1T = t1.T
t2 = np.dot(t21T, t1T)
print(t2)

t3 = np.dot(t1T, t21T)
print(t3)

[[26 38 44]
 [30 63 54]
 [ 3 10  5]]
[[4702 6270  741]
 [2858 3972  508]
 [1864 2544  315]]
[[2212 1950 1863]
 [3939 3564 3171]
 [3842 3402 3213]]


In [ ]:
print(np.linalg.matrix_rank(A))
print(np.linalg.det(A))
print(np.trace(A))
print(np.linalg.pinv(A))

3
16.999999999999993
18
[[-0.05882353  0.17647059 -0.58823529]
 [-0.52941176  0.58823529 -1.29411765]
 [ 1.05882353 -1.17647059  3.58823529]]


In [ ]:
print(np.concatenate((A, B), axis = 0))
print(np.reshape(A, -1))

[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]
 [ 2  3  4]
 [ 0  4  2]
 [ 3  2  1]]
[10  1  2  9  7  4  0  2  1]


In [1]:
import pandas as pd

In [2]:
dataset = pd.read_excel("Week4-data_06.xlsx")
dataset

Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1       PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
3      NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
4          TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   
..                   ...    ...                        ...            ...   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
639      NGUYỄN TƯỜNG VY  60622        THCS Trịnh Hoài Đức              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  
0              2.0        3.0  9.00   8.9  8.75  29.65         1  
1              7.0        2.0  8.75   9.6  9.25  29.60         2  
2              7.0        2.0  8.25   9.6  9.25  29.10         3  
3              7.0        NaN  8.75  10.0  9.25  28.00         4  
4              2.0        2.0  8.25   9.7  8.00  27.95         5  
..             ...        ...   ...   ...   ...    ...       ...  
636            8.0        NaN  6.75   3.9  2.75  13.40       637  
637           30.0        NaN  6.25   3.6  3.50  13.35       638  
638            8.0        NaN  6.00   3.5  3.25  12.75       639  
639            8.0        NaN  6.25   3.2  3.00  12.45       640  
640           30.0        NaN  5.50   2.4  3.75  11.65       641  

[641 rows x 11 columns]

In [3]:
dataset.loc[dataset['Mã số'] == 60457]

Tên  Mã số   Trường cấp 2  Nguyện vọng 1  Nguyện vọng 2  \
100  NGUYỄN LÊ PHƯƠNG TÂM  60457  THCS Phú Long              6            7.0   

     Điểm cộng  Văn  Anh  Toán   Tổng  Xếp hạng  
100        2.0  7.0  9.4  6.25  24.65       101

In [4]:
dataset.loc[dataset['Tên'] == 'NGUYỄN ĐÌNH NHÂN']

Tên  Mã số          Trường cấp 2  Nguyện vọng 1  \
106  NGUYỄN ĐÌNH NHÂN  60350  THCS Nguyễn Văn Tiết              6   

     Nguyện vọng 2  Điểm cộng  Văn  Anh  Toán  Tổng  Xếp hạng  
106            7.0        2.0  6.0  8.6   8.0  24.6       107

In [5]:
dataset.loc[(dataset['Mã số'] >= 60004) & (dataset['Mã số'] <= 60200)]

Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
5     PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
7         ĐẶNG MINH CHÂU  60067  THCS Nguyễn Thị Minh Khai              6   
10         NGÔ MỸ GIA AN  60004    THCS-THPT Nguyễn Khuyến              6   
..                   ...    ...                        ...            ...   
634      NGUYỄN TUẤN ANH  60033            THCS Thanh Bình              6   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn  Anh  Toán   Tổng  Xếp hạng  
0              2.0        3.0  9.00  8.9  8.75  29.65         1  
2              7.0        2.0  8.25  9.6  9.25  29.10         3  
5              7.0        NaN  8.50  9.9  9.50  27.90         6  
7              2.0        NaN  9.00  9.9  9.00  27.90         8  
10             2.0        2.0  7.50  9.3  8.75  27.55        11  
..             ...        ...   ...  ...   ...    ...       ...  
634            8.0        NaN  3.50  4.7  5.50  13.70       635  
636            8.0        NaN  6.75  3.9  2.75  13.40       637  
637           30.0        NaN  6.25  3.6  3.50  13.35       638  
638            8.0        NaN  6.00  3.5  3.25  12.75       639  
640           30.0        NaN  5.50  2.4  3.75  11.65       641  

[197 rows x 11 columns]

In [6]:
dataset['Điểm TB'] = (dataset.iloc[:, 6:9].mean(axis = 1)).round(2)
dataset

Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0           QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1       PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2         TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
3      NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
4          TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   
..                   ...    ...                        ...            ...   
636        TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
637  DOÃN THỊ PHƯƠNG ANH  60017            THCS Bình Chiểu              6   
638       CÙ THỊ GIA HÂN  60151     THCS Nguyễn Trung Trực              6   
639      NGUYỄN TƯỜNG VY  60622        THCS Trịnh Hoài Đức              6   
640         LƯU QUANG ĐÔ  60108        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  Điểm TB  
0              2.0        3.0  9.00   8.9  8.75  29.65         1     8.88  
1              7.0        2.0  8.75   9.6  9.25  29.60         2     9.20  
2              7.0        2.0  8.25   9.6  9.25  29.10         3     9.03  
3              7.0        NaN  8.75  10.0  9.25  28.00         4     9.33  
4              2.0        2.0  8.25   9.7  8.00  27.95         5     8.65  
..             ...        ...   ...   ...   ...    ...       ...      ...  
636            8.0        NaN  6.75   3.9  2.75  13.40       637     4.47  
637           30.0        NaN  6.25   3.6  3.50  13.35       638     4.45  
638            8.0        NaN  6.00   3.5  3.25  12.75       639     4.25  
639            8.0        NaN  6.25   3.2  3.00  12.45       640     4.15  
640           30.0        NaN  5.50   2.4  3.75  11.65       641     3.88  

[641 rows x 12 columns]

In [7]:
print((dataset['Văn'].mean()).round(2))
print((dataset['Anh'].mean()).round(2))
print((dataset['Toán'].mean()).round(2))

7.29
7.0
7.11


In [8]:
dataset['ĐiểmTB_T-A'] = (dataset.iloc[:, 7:9].mean(axis = 1)).round(2)
datasetTA = dataset.sort_values('ĐiểmTB_T-A', ascending = False)
datasetTA.iloc[99]

Tên              NGUYỄN NGỌC QUỲNH ANH
Mã số                            60010
Trường cấp 2       THCS Trịnh Hoài Đức
Nguyện vọng 1                        6
Nguyện vọng 2                      8.0
Điểm cộng                          2.0
Văn                                7.5
Anh                                9.8
Toán                              6.75
Tổng                             26.05
Xếp hạng                            41
Điểm TB                           8.02
ĐiểmTB_T-A                        8.28
Name: 40, dtype: object

In [9]:
datasetToan = dataset.sort_values('Toán', ascending = False)
datasetToan

Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
8             LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa              6   
23           PHẠM THANH HÀ  60129  THCS Nguyễn Thị Minh Khai              6   
20             LƯU MINH ÂN  60037        THCS Trần Đại Nghĩa              6   
5       PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
11          NGUYỄN AN HOÀI  60169    THCS-THPT Nguyễn Khuyến              6   
..                     ...    ...                        ...            ...   
615     TRỊNH VĂN ANH KIỆT  60207        THCS Trịnh Hoài Đức              6   
631       NGUYỄN HUY HOÀNG  60174       TH-THCS-THPT Đức Trí              6   
639        NGUYỄN TƯỜNG VY  60622        THCS Trịnh Hoài Đức              6   
636          TRẦN NHẬT ANH  60032       THCS Nguyễn Văn Tiết              6   
630  HÀ NGUYỄN QUYỀN KHANH  60224        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  Điểm TB  \
8              7.0        NaN  8.75   9.3  9.75  27.80         9     9.27   
23             2.0        NaN  7.50   9.5  9.50  26.50        24     8.83   
20             7.0        NaN  7.75   9.4  9.50  26.65        21     8.88   
5              7.0        NaN  8.50   9.9  9.50  27.90         6     9.30   
11             2.0        NaN  8.00  10.0  9.50  27.50        12     9.17   
..             ...        ...   ...   ...   ...    ...       ...      ...   
615            8.0        NaN  7.00   6.0  3.00  16.00       616     5.33   
631            8.0        NaN  5.50   5.6  3.00  14.10       632     4.70   
639            8.0        NaN  6.25   3.2  3.00  12.45       640     4.15   
636            8.0        NaN  6.75   3.9  2.75  13.40       637     4.47   
630            8.0        NaN  7.00   5.4  1.75  14.15       631     4.72   

     ĐiểmTB_T-A  
8          9.52  
23         9.50  
20         9.45  
5          9.70  
11         9.75  
..          ...  
615        4.50  
631        4.30  
639        3.10  
636        3.32  
630        3.58  

[641 rows x 13 columns]

In [10]:
datasetTong = datasetToan.sort_values('Tổng', ascending = False)

In [11]:
datasetTong.sort_values('Điểm TB', ascending = False).head(300)


Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
3       NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
5      PHẠM LỢI NGỌC HIỀN  60158         THCS Châu Văn Liêm              6   
7          ĐẶNG MINH CHÂU  60067  THCS Nguyễn Thị Minh Khai              6   
8            LÊ MINH NGỌC  60334        THCS Trần Đại Nghĩa              6   
1        PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
..                    ...    ...                        ...            ...   
316     VŨ TRỊNH LINH NHI  60352              THCS Phú Long              6   
152      NGUYỄN THÁI LONG  60268              THCS Phú Long              6   
151  NGUYỄN THỊ THÙY TRÂM  60575        THCS Trịnh Hoài Đức              6   
321    LÊ NGUYỄN VĨ KHANG  60220              THCS Phú Long              6   
318    TRẦN TÔ THANH LIÊM  60245        THCS Trịnh Hoài Đức              6   

     Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  Điểm TB  \
3              7.0        NaN  8.75  10.0  9.25  28.00         4     9.33   
5              7.0        NaN  8.50   9.9  9.50  27.90         6     9.30   
7              2.0        NaN  9.00   9.9  9.00  27.90         8     9.30   
8              7.0        NaN  8.75   9.3  9.75  27.80         9     9.27   
1              7.0        2.0  8.75   9.6  9.25  29.60         2     9.20   
..             ...        ...   ...   ...   ...    ...       ...      ...   
316            7.0        NaN  7.00   6.6  8.25  21.85       317     7.28   
152            7.0        2.0  7.50   8.1  6.25  23.85       153     7.28   
151            8.0        2.0  5.75   8.6  7.50  23.85       152     7.28   
321            7.0        NaN  7.00   8.3  6.50  21.80       322     7.27   
318            8.0        NaN  6.25   8.8  6.75  21.80       319     7.27   

     ĐiểmTB_T-A  
3          9.62  
5          9.70  
7          9.45  
8          9.52  
1          9.43  
..          ...  
316        7.42  
152        7.18  
151        8.05  
321        7.40  
318        7.78  

[300 rows x 13 columns]

In [17]:
sinhvien1 = dataset[dataset['Mã số'] == 60575]
sinhvien2 = dataset[dataset['Mã số'] == 60602]

sinhvien2.fillna(0, inplace = True)

dataset['diem'] = dataset['Tổng'].subtract(dataset['Điểm cộng'])

diemsv1 = sinhvien1['Tổng'] - sinhvien1['Điểm cộng']
diemsv2 = sinhvien2['Tổng'] - sinhvien2['Điểm cộng']

print(diemsv1)
print(diemsv2)

151    21.85
dtype: float64
191    23.3
dtype: float64


<ipython-input-17-b16ff5669301>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sinhvien2.fillna(0, inplace = True)
